models/Car.php
<?php

namespace app\models;

/**
 * This is the model class for table "cars".
 *
 * @property int $id
 * @property int|null $brand_id
 * @property int|null $model_id
 * @property int|null $mileage
 * @property int|null $price
 * @property string|null $phone
 *
 * @property CarOption[] $carOptions
 * @property CarPhoto[] $carPhotos
 * @property Brand $brand
 * @property BrandModel $model
 */
class Car extends \yii\db\ActiveRecord
{

    /**
     * @var array
     */
    public $photos     = [];
    /**
     * @var array
     */
    public $carOptions = [];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cars';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['brand_id', 'model_id', 'price', 'phone', 'photos'], 'required'],
            [['brand_id', 'model_id', 'mileage', 'price'], 'integer'],
            [['phone'], 'string', 'max' => 255],
            [['brand_id'], 'exist', 'skipOnError' => true, 'targetClass' => Brand::class, 'targetAttribute' => ['brand_id' => 'id']],
            [['model_id'], 'exist', 'skipOnError' => true, 'targetClass' => BrandModel::class, 'targetAttribute' => ['model_id' => 'id']],
            [['photos'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg, jpeg', 'maxFiles' => 3],
            [['carOptions'], 'safe'],
            ['carOptions', 'each', 'rule' => ['integer']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'         => 'ID',
            'brand_id'   => 'Марка',
            'model_id'   => 'Модель',
            'mileage'    => 'Пробег',
            'price'      => 'Цена',
            'phone'      => 'Телефон',
            'photos'     => 'Фотографии',
            'carOptions' => 'Дополнительное оборудование (опции)',
        ];
    }

    /**
     * Gets query for [[CarOptions]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCarOptions()
    {
        return $this->hasMany(CarOption::class, ['car_id' => 'id']);
    }


    /**
     * Gets query for [[CarPhotos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCarPhotos()
    {
        return $this->hasMany(CarPhoto::class, ['car_id' => 'id']);
    }

    /**
     * Gets query for [[Brand]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getBrand()
    {
        return $this->hasOne(Brand::class, ['id' => 'brand_id']);
    }

    /**
     * Gets query for [[Model]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getModel()
    {
        return $this->hasOne(BrandModel::class, ['id' => 'model_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     * @throws \yii\base\InvalidConfigException
     */
    public function getOptions()
    {
        return $this->hasMany(Option::class, ['id' => 'option_id'])
                    ->viaTable(CarOption::tableName(), ['car_id' => 'id']);
    }

    /**
     * Сохраняет фотографии
     */
    public function savePhotos()
    {
        foreach ($this->photos as $file)
        {
            $fileName = uniqid() . '.' . $file->extension;
            $file->saveAs('files/' . $fileName);
            $photo       = new CarPhoto();
            $photo->name = $fileName;
            $photo->link('car', $this);
        }

        return true;
    }

    /**
     * Сохраняет опции
     */
    public function saveOptions()
    {
        CarOption::deleteAll(['car_id' => $this->id]);
        if ($this->carOptions)
        {
            foreach ($this->carOptions as $option_id)
            {
                $carOption            = new CarOption();
                $carOption->option_id = $option_id;
                $carOption->link('car', $this);
            }
        }

        return true;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->brand->name . ' ' . $this->model->name;
    }

    /**
     * @return bool
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function beforeDelete()
    {
        foreach ($this->carPhotos as $photo)
        {
            $photo->delete();
        }

        return parent::beforeDelete();
    }
}

models/CarPhoto.php
<?php

namespace app\models;

use app\components\MyImage;
use Imagine\Image\ImageInterface;
use Yii;
use yii\imagine\Image;

/**
 * This is the model class for table "car_photos".
 *
 * @property int $id
 * @property int|null $car_id
 * @property string|null $name
 *
 * @property Car $car
 */
class CarPhoto extends \yii\db\ActiveRecord
{
    /**
     *
     */
    const THUMB_1_WIDTH = 146;
    /**
     *
     */
    const THUMB_1_HEIGHT = 106;
    /**
     *
     */
    const THUMB_1_DIR = '146x106';

    /**
     *
     */
    const THUMB_2_WIDTH = 720;
    /**
     *
     */
    const THUMB_2_HEIGHT = 540;
    /**
     *
     */
    const THUMB_2_DIR = '720x540';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'car_photos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['car_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['car_id'], 'exist', 'skipOnError' => true, 'targetClass' => Car::class, 'targetAttribute' => ['car_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'     => 'ID',
            'car_id' => 'Car ID',
            'name'   => 'Name',
        ];
    }

    /**
     * Gets query for [[Car]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCar()
    {
        return $this->hasOne(Car::class, ['id' => 'car_id']);
    }


    /**
     * @return string
     */
    public function getOriginal()
    {
        return '/files/' . $this->name;
    }

    /**
     * @return string
     */
    public function getThumbnail1()
    {
        return '/files/' . self::THUMB_1_DIR . '/' . $this->name;
    }

    /**
     * @return string
     */
    public function getThumbnail2()
    {
        return '/files/' . self::THUMB_2_DIR . '/' . $this->name;
    }

    /**
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        // Make thumb 1
        MyImage::thumbnail(Image::autorotate(Yii::getAlias('@webroot' . $this->getOriginal())), self::THUMB_1_WIDTH, self::THUMB_1_HEIGHT, ImageInterface::THUMBNAIL_INSET)
               ->save(Yii::getAlias('@webroot' . $this->getThumbnail1()), ['quality' => 90]);

        // Make thumb 2
        MyImage::thumbnail(Image::autorotate(Yii::getAlias('@webroot' . $this->getOriginal())), self::THUMB_2_WIDTH, self::THUMB_2_HEIGHT, ImageInterface::THUMBNAIL_INSET)
               ->save(Yii::getAlias('@webroot' . $this->getThumbnail2()), ['quality' => 90]);

        parent::afterSave($insert, $changedAttributes);
    }


    /**
     *{@inheritdoc}
     */
    public function afterDelete()
    {
        $original = Yii::getAlias('@webroot' . $this->getOriginal());
        $thumb1   = Yii::getAlias('@webroot' . $this->getThumbnail1());
        $thumb2   = Yii::getAlias('@webroot' . $this->getThumbnail2());

        if (file_exists($original)) unlink($original);
        if (file_exists($thumb1)) unlink($thumb1);
        if (file_exists($thumb2)) unlink($thumb2);

        return parent::afterDelete();
    }

}

controllers/CarsController.php
<?php

namespace app\controllers;

use app\repositories\CarRepository;
use \Yii;
use app\models\Car;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


class CarsController extends \yii\web\Controller
{

    /**
     * @var CarRepository
     */
    private $repo;

    /**
     * CarsController constructor.
     * @param $id
     * @param $module
     * @param array $config
     * @param CarRepository $repo
     */
    public function __construct($id, $module, $config = [], CarRepository $repo)
    {
        parent::__construct($id, $module, $config);
        $this->repo = $repo;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return ['verbs' => [
            'class'   => VerbFilter::class,
            'actions' => [
                '*'       => ['GET'],
                'add'     => ['GET', 'POST'],
                'add-car' => ['GET', 'POST'],
            ],
        ],];
    }

    /**
     * @return string
     */
    public function actionList()
    {
        list($cars, $pages) = $this->repo->getCarsPaginated();

        return $this->render('cars', ['cars' => $cars, 'pages' => $pages]);
    }


    /**
     * @param $id
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionOne($id)
    {
        $car = $this->repo->getCarById($id);
        if (!$car)
        {
            throw new \yii\web\NotFoundHttpException();
        }

        return $this->render('one', ['car' => $car]);
    }


    public function actionAddCar()
    {
        $service = Yii::$container->get('CarServiceInterface');
        $brands  = $this->repo->getBrandsForDropDownList();
        $options = $this->repo->getOptionsForDropDownList();
        $models  = [];

        if (Yii::$app->request->isPost)
        {
            if ($service->add(Yii::$app->request->post(), UploadedFile::getInstancesByName('Car[photos]')))
            {
                $this->redirect(['cars/one', 'id' => $service->getCar()->id]);
            }

            $models = $this->repo->getBrandModelsByBrandId($service->getCar()->brand_id);
        }

        return $this->render('form', ['model'   => $service->getCar(),
                                      'brands'  => $brands,
                                      'models'  => $models,
                                      'options' => $options,
        ]);
    }


    /** OLD method without service
     * @return string
     */
    /*public function actionAdd()
    {
        $car     = new Car();
        $brands  = $this->repo->getBrandsForDropDownList();
        $models  = [];
        $options = $this->repo->getOptionsForDropDownList();

        if (Yii::$app->request->isPost)
        {
            $car->load(Yii::$app->request->post());
            $car->photos = UploadedFile::getInstances($car, 'photos');

            if ($car->validate())
            {
                $car->save(false);
                $car->savePhotos();
                $car->saveOptions();

                $this->redirect(['cars/one', 'id' => $car->id]);
            }

            $models = $this->repo->getBrandModelsByBrandId($car->brand_id);
        }


        return $this->render('form', ['model'   => $car,
                                      'brands'  => $brands,
                                      'models'  => $models,
                                      'options' => $options,
        ]);
    }*/


}

views/cars/_list.php
<?php foreach ($cars as $key => $car): ?>
    <div class="row <?=($key%2)?'row_bg_gray':'row_bg_white'?>">
        <div class="col-md-3 car_img_cell">
            <img src="<?= $car->carPhotos[0]->thumbnail1 ?>" alt="<?= $car->name ?>" class="img"/>
        </div>
        <div class="col-md-3 car_data_cell">
            <a href="<?= \yii\helpers\Url::to(['cars/one', 'id' => $car->id]) ?>"><?= $car->name ?></a>
        </div>
        <div class="col-md-3 car_data_cell">
            <?= \Yii::$app->formatter->asInteger($car->price) ?> руб
        </div>
        <div class="col-md-3 car_data_cell">
            <a href="#" data-id="<?=$car->id?>" class="delete">Удалить</a>
        </div>
    </div>
<?php endforeach; ?>
<div class="row">
    <?= \yii\widgets\LinkPager::widget([
        'pagination' => $pages,
    ]); ?>
</div>

views/cars/add.php
<?php
/* @var $this yii\web\View */
?>
<h1>cars/add</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

views/cars/cars.php
<div class="container" id="cars">
    <?= $this->render('_list', ['cars' => $cars, 'pages' => $pages]) ?>
</div>

views/cars/form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CarForm */
/* @var $form ActiveForm */
?>
<div class="cars-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'brand_id')->dropDownList($brands, ['id' => 'brand_id', 'prompt' => 'Выберите марку']) ?>
    <?= $form->field($model, 'model_id')->dropDownList($models, ['id' => 'model_id', 'prompt' => 'Для начала выберите марку']) ?>
    <?= $form->field($model, 'mileage') ?>
    <?= $form->field($model, 'price') ?>
    <?= $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::class, [
        'mask' => '+7 (999) 999-99-99',])?>
    <?= $form->field($model, 'photos[]')->fileInput(['multiple' => true])->hint('Выберите несколько файлов, используя клавишу CTRL') ?>
    <?= $form->field($model, 'carOptions')->checkboxList($options, ['separator' => ' | ', 'id'=>'hiddenCheckbox']) ?>
    <?php /*foreach($)*/ ?>
    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div><!-- cars-form -->

views/cars/one.php
<?php

\app\assets\FancyBoxAsset::register($this);

?>
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-20">
            <div>
                <a data-fancybox="gallery" href="<?= $car->carPhotos[0]->original ?>" id="photo">
                    <img src="<?= $car->carPhotos[0]->thumbnail2 ?>" alt="<?= $car->name ?>" class="img"/>
                </a>
            </div>
            <div>
                <?php foreach ($car->carPhotos as $photo): ?>
                    <a href="#"><img src="<?= $photo->thumbnail1 ?>" alt="<?= $car->name ?>"
                                     data-thumb2="<?= $photo->thumbnail2 ?>" data-original="<?= $photo->original ?>"
                                     class="gallery img"/></a>
                <?php endforeach ?>
            </div>
        </div>
        <div class="col-md-4 mt-20">
            <h1><?= $car->name ?></h1>
            <dl>
                <?php if ($car->mileage): ?>
                    <dt><?=$car->getAttributeLabel('mileage')?>:</dt>
                    <dd><?= \Yii::$app->formatter->asInteger($car->mileage) ?> км</dd>
                <?php endif ?>
                <dt><?=$car->getAttributeLabel('price')?>:</dt>
                <dd><?= \Yii::$app->formatter->asInteger($car->price) ?> руб</dd>
                <dt><?=$car->getAttributeLabel('phone')?>:</dt>
                <dd><?= $car->phone ?></dd>
                <?php if ($car->options): ?>
                    <dt><?=$car->getAttributeLabel('carOptions')?>:</dt>
                    <dd>
                        <ul>
                            <?php foreach ($car->options as $option): ?>
                                <li><?= $option->name ?></li>
                            <?php endforeach ?>
                        </ul>
                    </dd>
                <?php endif ?>
            </dl>
        </div>
    </div>
</div>